version: '3.8'

services:
  taskreload:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/root/data
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/tasks"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
